Story/urls.py
from django.urls import path

from . import views

app_name = 'Story'

urlpatterns = [
    path('', views.index, name='index'),
]

Story5/urls.py
from django.urls import path
from . import views

app_name = 'Story5'

urlpatterns = [
    path('', views.courses, name="courses"),
    path('add/', views.addCourse, name="form"),
    path('description/<int:id>', views.descCourse, name="description"),
    path('delete/<int:id>', views.deleteCourse, name="delete"),
]

Story6/urls.py
from django.urls import path
from . import views

app_name = 'Story6'

urlpatterns = [
    path('', views.view, name="activities"),
    path('addPerson/<int:id>', views.addPerson, name="addPerson"),
    path('addActivity/', views.addActivity, name="addActivity"),
    path('delPerson/<int:id>', views.delPerson, name="deletePerson"),
    path('delActivity/<int:id>', views.delActivity, name="deleteActivity")
]

ediw_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('story1/', include('Story.urls', namespace='Story')),  
    path('courses/', include('Story5.urls', namespace='courses')),
    path('activities/', include('Story6.urls', namespace='activities')),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path("facts/", views.facts_page, name="facts"),
]

Story/models.py
from django.db import models

# Create your models here.

Story5/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class Course(models.Model):
	courseName = models.CharField(max_length=100)
	lecturer = models.CharField(max_length=50)
	credit = models.CharField(max_length=5)
	semester = models.CharField(max_length=5)

	def __str__(self):
		return self.courseName

Story6/models.py
from django.db import models

class Activities(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name

class Person(models.Model):
	name = models.CharField(max_length=50)
	activity = models.ManyToManyField(Activities)

	def __str__(self):
		return self.name

home/models.py
from django.db import models

# Create your models here.

Story5/forms.py
from django.forms import ModelForm
from .models import Course

class CourseForm(ModelForm):
	class Meta:
		model = Course
		fields = '__all__'
	error_messages = {
		'required' : 'Please fill this field'
	}
	

Story6/forms.py
from django.forms import ModelForm
from .models import Activities, Person

class ActivityForm(ModelForm):
  class Meta:
    model = Activities
    fields = '__all__'
  error_messages = {
    'required' : 'Please fill this field'
  }

class PersonForm(ModelForm):
  class Meta:
    model = Person
    fields = '__all__'
  error_messages = {
    'required' : 'Please fill this field'
  }

Story/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	context = {
		"type" : "Story"
	}
	return render(request, 'home/index.html', context)

Story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import CourseForm


def courses(request):
	course = Course.objects.all()
	context = {
		"type" : "course",
		"courses" : course
	}
	return render(request, 'home/courses.html', context)


def addCourse(request):
	form = CourseForm()
	if request.method == 'POST':
		form = CourseForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('Story5:courses')
	context = {
		'form' : form
	}
	return render(request, 'home/form.html', context)


def descCourse(request, id):
	desc = Course.objects.get(id=id)
	context = {
		'desc' : desc
	}
	return render(request, 'home/courseDesc.html', context)


def deleteCourse(request, id):
	if request.method == 'POST':
		course = Course.objects.get(id=id)
		course.delete()
		
	return redirect('Story5:courses')

Story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import ActivityForm, PersonForm
# Create your views here.

def view(request):
	person = Person.objects.all()
	activity = Activities.objects.all()
	person_form = PersonForm()
	activity_form = ActivityForm()
	context = {
		"type" : "activities",
		"person" : person,
		"activities" : activity,
		"person_form": person_form,
		"activity_form": activity_form,
	}
	print(person)
	return render(request, 'home/activities.html', context)

def addPerson(request, id):
	form = PersonForm()
	act = Activities.objects.get(id=id)

	if request.method == 'POST':
		form = PersonForm(request.POST)
		person = Person.objects.create(name=request.POST["name"])
		if form.is_valid():
			person.save()
			person.activity.add(act)
			return redirect('Story6:activities')
	return redirect('Story6:activities')

def addActivity(request):
	form = ActivityForm()
	if request.method ==  'POST':
		form = ActivityForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('Story6:activities')

def delPerson(request, id):
	if request.method == 'POST':
		person = Person.objects.get(id=id)
		person.delete()
	return redirect('Story6:activities')

def delActivity(request, id):
	if request.method == 'POST':
		activity = Activities.objects.get(id=id)
		activity.delete()
	return redirect('Story6:activities')

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	context = {
		"type" : "homepage"
	}
	return render(request, 'home/homepage.html', context)

def facts_page(request):
	context = {
		"type" : "facts"
	}
	return render(request, 'home/facts-page.html', context)

Story/templates/home/index.html
{% extends "home/base.html" %}
{% block content %}
{% load static %}

<div style="padding-left: 20px; padding-top: 20px; padding-bottom: 20px;">
	<img src="{% static 'home/images/Iqbal_formal3.jpg' %}" style="width: 20%" alt="Foto gw kok gak ngeload sih">
	<h2>Biodata</h2>
	<p>Nama: Alif Iqbal Hazairin</p>
	<p>Jurusan: Ilmu Komputer</p>
	<p>NPM: 1906398282</p>
	<p>Angkatan: 2019</p>
	<p>Hobi: Nonton youtube</p>
	<p>Deskripsi: Cuma mahasiswa biasa</p>
	<hr>
	<h2>Riwayat Pendidikan</h2>
	<table border="1" cellpadding="5" cellspacing="0">
		<tr>
			<th align="left">SD</th>
			<td>SDN 04 Ujung Menteng Jakarta Timur</td>
			<td>2007-2013</td>
		</tr>
		<tr>
			<th align="left">SMP</th>
			<td>MTs Pondok Pesantren Modern Sahid</td>
			<td>2013-2016</td>
		</tr>
		<tr>
			<th align="left">SMA</th>
			<td>MAN Insan Cendekia Serpong</td>
			<td>2016-2019</td>
		</tr>
		<tr>
			<th align="left">Perguruan Tinggi</th>
			<td>Fakultas Ilmu Komputer Universitas Indonesia</td>
			<td>2019-Sekarang</td>
		</tr>
	</table>
</div>	
{% endblock %}

Story5/templates/home/courseDesc.html
{% extends "home/base.html" %}
{% block content %}
{% load static %}
<div class="container-fluid bg-color-bisque">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="..">Courses</a></li>
      <li class="breadcrumb-item active" aria-current="page">Description</li>
    </ol>
  </nav>
  <h2>Course Details</h2>
  <table class="table" style="text-align: left;">
      <tbody>
          <tr>
              <th scope="row">Name</th>
              <td>{{ desc.courseName }}</td>
          </tr>
          <tr>
              <th scope="row">Lecturer</th>
              <td>{{ desc.lecturer }}</td>
          </tr>
          <tr>
              <th scope="row">Credit</th>
              <td>{{ desc.credit }}</td>
          </tr>
          <tr>
              <th scope="row">Semester</th>
              <td>{{ desc.semester }}</td>
          </tr>
        </tbody>
  </table>
    <!-- Button trigger modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">
    Delete
  </button>

<!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Delete</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>You are about to delete {{ desc.courseName }}. Press proceed to continue deleting.</p> </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <form action="{% url 'Story5:delete' desc.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Proceed</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

Story5/templates/home/courses.html
{% extends "home/base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">

<div class="container-fluid bg-color-red course-sect">
	<h1 class="text-center" id="course-sect-title">Courses</h1>
	<nav aria-label="breadcrumb" style="background-color: #d81029;">
	  	<ol class="breadcrumb">
	    	<li class="breadcrumb-item active" aria-current="page">Courses</li>
	  	</ol>
	</nav>
	<div class="row justify-content-center">
		<div class="col-lg-10">
			<h4 class="text-left">My Courses</h4>
			<div class="container">
				<ul class="list-group list-group-flush">

				  	{% for course in courses %}

					  	<li class="list-group-item" style="background-color: #d81029">
					  		<a href="description/{{ course.id }}" id="course-link">{{ course.courseName }}</a>
					  	</li>
				  	
				  	{% endfor %}
				  	
				</ul>
				<a type="button" class="btn btn-light" href="{% url 'Story5:form' %}">Add</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

Story5/templates/home/form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container-fluid bg-color-red">
  <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
      <button type="submit" class="btn btn-light">Submit</button>
      <a type="button" class="btn btn-default" href="{% url 'Story5:courses' %}">Cancel</a>
  </form>
</div>
{% endblock %}

Story6/templates/home/activities.html
{% extends "home/base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home/styles.css' %}">

<div class="container-fluid bg-color-bisque">
  <h1 class="text-center" id="activities-sect-title">Activities</h1>
  <div class="row" id="activity-input">
    <div class="col3"></div>
    <div class="col6">
      <div class="card">
        <div class="card-body">
          <h3 class="text-center">Add Activity</h3>
          <form action="{% url 'Story6:addActivity' %}" method="POST">
            {% csrf_token %}
            <div class="col-form-labelgroup">
              {{activity_form.name}}
            </div>
            <button type="submit" class="btn btn-primary">Add</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="row">

    {% for activity in activities %}

    <div class="col-12 col-lg-6 d-flex align-item-stretch justify-content-center activity-container">
      <div class="card">
        <div class="card-header">
          <h3 style="display: inline;">{{ activity.name }}</h3>
          <form action="{% url 'Story6:deleteActivity' activity.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
        <ul class="list-group list-group-flush">
            
          {% for orang in person %}

            {% if orang.activity.id == activity.id %}

            <li class="list-group-item">
              <p>{{orang.activity.id}}</p>
              <p>{{activity.id}}</p>
              <!-- <p>{{ orang.name }}</p> -->
            </li>

            {% endif %}

          {% endfor %}

        </ul>
        <!-- button trigger modal -->
        <form action="{% url 'Story6:addPerson' activity.id %}" method="POST">
            {% csrf_token %}
            {{ person_form.name }}
            <input type="select" name="activity" value="{activity.id}" hidden>
          <button type="submit" class="btn btn-light">Add</button>
        </form>
      </div>
    </div>
  {% endfor %}
  </div>
  <!-- modal -->
  <!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <form action="addPerson/{{activity.id}}" method="POST">
            <div class="form-group">
              {% csrf_token %}
              <label for="recipient-name" class="col-form-label">Enter Name</label>
              {{ person_form.name }}
            </div>
          
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
              <button type="submit" class="btn btn-primary">Add</button>
            </div>
          </form>
        </div>
      </div> -->

      

  </div>
</div>
{% endblock %}

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
	<!-- nanti link nya diganti jadi yang pake django -->
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/bootstrap.css' %}">

	<title>Iqbal Hazairin's</title>
</head>
<body>

	{% if type == "homepage" %}
	<nav class="navbar navbar-expand-lg navbar-dark bg-color-red fixed-top">
	    <a class="navbar-brand" href="#"><img src="{% static 'home/images/logogw.png' %}" alt="gambarnya masih di folder tugas" id="logo"></a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	   		<span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNavDropdown">
		    <ul class="navbar-nav">
			    <li class="nav-item active">
			    	<a class="nav-link" href="#">home<span class="sr-only">(current)</span></a>
			    </li>
			    <li class="nav-item dropdown active">
			    	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          menu
			    	</a>
				    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
				    	<a class="dropdown-item" href="{% url 'home:facts' %}">My Facts</a>
				    	<a class="dropdown-item" href="{% url 'Story:index' %}">Story 1</a>
				    	<a class="dropdown-item" href="{% url 'Story5:courses' %}">Courses</a>
				    	<a class="dropdown-item" href="{% url 'Story6:activities' %}">My Activities</a>
				    </div>
			    </li>
			    <li class="nav-item active">
			    	<a class="nav-link" href="#journey">my journey</a>
			    </li>
			    <li class="nav-item active">
			    	<a class="nav-link" href="#exp">experience</a>
			    </li>
			    <li class="nav-item active">
			    	<a class="nav-link" href="#skills">skills</a>
			    </li>
			    <li class="nav-item active">
			    	<a class="nav-link" href="#contact">contact me</a>
			    </li>
		    </ul>
	  	</div>
	</nav>

	{% elif type == "facts" %}
	<nav class="navbar navbar-expand-lg navbar-dark bg-color-red fixed-top">
	    <a class="navbar-brand" href=""><img src="{% static 'home/images/logogw.png' %}" alt="gambarnya masih di folder tugas" id="logo"></a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	   		<span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNavDropdown">
		    <ul class="navbar-nav">
			    <li class="nav-item active">
			    	<a class="nav-link" href="{% url 'home:index' %}">home<span class="sr-only">(current)</span></a>
			    </li>
			    <li class="nav-item dropdown active">
			    	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          menu
			    	</a>
			    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
				    <a class="dropdown-item" href="#">My Facts</a>
				    <a class="dropdown-item" href="{% url 'Story:index' %}">Story 1</a>
				    <a class="dropdown-item" href="{% url 'Story5:courses' %}">Courses</a>
				    <a class="dropdown-item" href="{% url 'Story6:activities' %}">My Activities</a>
			    </div>
			    </li>
			    <li class="nav-item active">
			    	<a class="nav-link" href="#contact">contact me</a>
			    </li>
		    </ul>
	  	</div>
	</nav>

	{% elif type == "Story" %}
	<nav class="navbar navbar-expand-lg navbar-dark bg-color-red sticky-top">
	    <a class="navbar-brand" href=""><img src="{% static 'home/images/logogw.png' %}" alt="gambarnya masih di folder tugas" id="logo"></a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	   		<span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNavDropdown">
		    <ul class="navbar-nav">
			    <li class="nav-item active">
			    	<a class="nav-link" href="{% url 'home:index' %}">home<span class="sr-only">(current)</span></a>
			    </li>
			    <li class="nav-item dropdown active">
			    	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          menu
			    	</a>
			    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
				    <a class="dropdown-item" href="{% url 'home:facts' %}">my facts</a>
				    <a class="dropdown-item" href="#">Story 1</a>
				    <a class="dropdown-item" href="{% url 'Story5:courses' %}">Courses</a>
				    <a class="dropdown-item" href="{% url 'Story6:activities' %}">My Activities</a>
			    </div>
			    </li>
			    <li class="nav-item active">
			    	<a class="nav-link" href="#contact">contact me</a>
			    </li>
		    </ul>
	  	</div>
	</nav>

	{% else %}
	<nav class="navbar navbar-expand-lg navbar-dark bg-color-red sticky-top">
	    <a class="navbar-brand" href=""><img src="{% static 'home/images/logogw.png' %}" alt="gambarnya masih di folder tugas" id="logo"></a>
	    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	   		<span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNavDropdown">
		    <ul class="navbar-nav">
			    <li class="nav-item active">
			    	<a class="nav-link" href="{% url 'home:index' %}">home<span class="sr-only">(current)</span></a>
			    </li>
			    <li class="nav-item dropdown active">
			    	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			          menu
			    	</a>
			    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
				    <a class="dropdown-item" href="{% url 'home:facts' %}">my facts</a>
				    <a class="dropdown-item" href="{% url 'Story:index' %}">Story 1</a>
				    <a class="dropdown-item" href="{% url 'Story5:courses' %}">Courses</a>
				    <a class="dropdown-item" href="{% url 'Story6:activities' %}">My Activities</a>
			    </div>
			    </li>
			    <li class="nav-item active">
			    	<a class="nav-link" href="#contact">contact me</a>
			    </li>
		    </ul>
	  	</div>
	</nav>
	{% endif %}

	{% block content %}
	{% endblock %}


	<footer id="contact">
		<div class="row">
			<div class="col-sm-6">
				<p>contact me on</p>
			</div>
			<div class="col-sm-6">
				<a href="https://twitter.com/ediwhz"><img src="{% static 'home/images/twitterlogo.png' %}" class="contact-img"></a>
				<a href="https://www.instagram.com/e___diw/"><img src="{% static 'home/images/iglogo.png' %}" class="contact-img"></a>
				<a href="https://www.linkedin.com/in/alif-iqbal-hazairin-302645156/"><img src="{% static 'home/images/LinkedIn-Logo-02.png' %}" class="contact-img"></a>
			</div>
		</div>
		<div class="row">
			<span class="col">
				<p id="copyright">Copyright &#169; 2020 Alif I Hazairin</p>
			</span>
		</div>
	</footer>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static 'home/scripts/script.js' %}"></script>
</body>
</html>

home/templates/home/facts-page.html
{% extends "home/base.html" %}
{% block content %}
{% load static %}

    <div class="fact-section container-fluid bg-color-bisque">
        <h1 class="text-center" id="fact-sect-title">Facts About Me</h1>
        <ul>
            <li>
                <div class="fact-box">
                    <div class="facts">
                        <p class="fact-text">19 years old at the moment.</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="fact-box">
                    <div class="facts">
                        <p class="fact-text">Born and live in Jakarta.</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="fact-box">
                    <div class="facts">
                        <p class="fact-text">Listen to many music genres, such as rock, hip hop, pop, 
                            classic, sometimes dangdut, and currently listening to classical rock. 
                            Yeah, like Beethoven but played by MCR.</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="fact-box">
                    <div class="facts">
                        <p class="fact-text">I was a competitor in National Science Olympiad in Earth Science
                            field.</p>
                    </div>
                </div>
            </li>
            <li>
                <div class="fact-box" id="question-3">
                    <div class="facts">
                        <p class="fact-text">Attack on Titan fan but also watch JoJo"s Bizarre Adventure.</p>
                    </div>
                </div>
            </li>
        </ul>
    </div>

{% endblock %}

home/templates/home/homepage.html
{% extends "home/base.html" %}
{% block content %}
{% load static %}

	<!-- Jumbotron -->
	<div class="jumbotron-fluid" id="jumbotron-margin">
	  	<div class="container-fluid bg-color-red">
	  		<div class="row">
	  			<div class="col-sm-7">
	    			<h1 class="ml-5" id="greetings">Hello there!</h1>
	    			<a href="https://www.youtube.com/watch?v=rEq1Z0bjdwc" target="_blank" class="custom-font" id="easteregg">&#40; general kenobi &#41;</a>
	    		</div>
	    		<div class="col-sm-5">
	    			<img src="{% static 'home/images/potrait1.png' %}" alt="gambarnya masih di folder tugas" id="frontphoto">
	    			<img src="{% static 'home/images/potrait1solid.png' %}" class="photo-shadow" id="frontphoto-shade">
	    			<img src="{% static 'home/images/potrait1solido75.png' %}" class="photo-shadow" id="frontphoto-shade2">
	    			<img src="{% static 'home/images/potrait1solido50.png' %}" class="photo-shadow" id="frontphoto-shade3">
	    		</div>
	    	</div>
	  	</div>
	</div>
	
	<!-- Desc -->
	<div class="desc-section container-fluid bg-color-bisque" id="about-me">
		<div class="row">
			<p class="desc-text">I'm Alif Iqbal Hazairin. You can call me Iqbal, but some of my friends call me Ediw. I'm currently studying programming and coding stuff in Faculty of Computer Science, University of Indonesia.
				<br>
			I love listening to music and have a lot of future plans, yet i'm still striving to be the best version of myself. Please, have a look at my web :)</p>
		</div>
	</div>

	<!-- Journey -->
	<div class="journey-section container-fluid bg-color-red" id="journey">
		<h1 class="text-center" id="journey-sect-title">My Journey</h1>
		<ul>
			<li>
				<div class="stack-box" id="sahid-cover">
					<img src="{% static 'home/images/logosahid.png' %}" class="journey-img">
					<p class="journey-text">MTs Sahid International Islamic Boarding School</p>
				</div>
			</li>
			<li>
				<div class="stack-box" id="ic-cover">
					<img src="{% static 'home/images/logoicremovebg.png' %}" class="journey-img">
					<p class="journey-text">MAN Insan Cendekia Serpong</p>
				</div>
			</li>
			<li>
				<div class="stack-box" id="ui-cover">
					<img src="{% static 'home/images/makarapacil.png' %}" class="journey-img">
					<p class="journey-text">Faculty of Computer Science, University of Indonesia</p>
				</div>
			</li>
		</ul>
	</div>

	<!-- Experience -->
	<section class="exp-section container-fluid bg-color-bisque" id="exp">
		<h1 class="text-center" id="exp-sect-title">Experiences</h1>
		<ul>
			<li>
				<div class="stack-box" id="exp-img-1">
					<p class="exp-text">Staff of logistics division Pemira Fasilkom 2019</p>
				</div>
			</li>
			<li>
				<div class="stack-box" id="exp-img-2">
					<p class="exp-text">Staff of consumption division Wisuda Ganjil 2019</p>
				</div>
			</li>
			<li>
				<div class="stack-box" id="exp-img-3">
					<p class="exp-text">Head of Mushala Prosperity Department FUKI Fasilkom 2020</p>
				</div>
			</li>
		</ul>
	</section>

	<!-- Skills -->
	<div class="skills-section container-fluid bg-color-red" id="skills">
		<h1 class="text-center" id="skills-sect-title">Skills</h1>
		<div class="row d-flex justify-content-center align-items-center" id="skills-container">
			<div class="col-sm-3">
				<img src="{% static 'home/images/pythonlogo.png' %}" class="skills-img">
				<p class="skills-text">Python</p>
			</div>
			<div class="col-sm-3">
				<img src="{% static 'home/images/javalogo.png' %}" class="skills-img">
				<p class="skills-text">Java</p>
			</div>
			<div class="col-sm-3">
				<img src="{% static 'home/images/htmllogo.png' %}" class="skills-img">
				<p class="skills-text">HTML</p>
			</div>
			<div class="col-sm-3">
				<img src="{% static 'home/images/csslogo.png' %}" class="skills-img">
				<p class="skills-text">CSS</p>
			</div>
		</div>
	</div>


{% endblock %}